version: '3.7'

services:
  db:
    container_name: django-site_db_1
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SKAL123vit
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - 5432:5432    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/code
      - C:/etc/config.json:/etc/config.json
    ports:
      - "8005:8005"
    depends_on:
      - db
    
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local