# Generated by Django 3.0.3 on 2020-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('file_name', models.CharField(blank=True, max_length=24)),
                ('profile_file', models.CharField(blank=True, max_length=30)),
                ('format_guess', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('ZAP', 'ZAP'), ('GAIA', 'GAIA'), ('LOPES', 'LOPES')], default='0', max_length=10)),
                ('url', models.CharField(default='', max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
