# Generated by Django 3.0.3 on 2020-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmltools', '0006_auto_20200426_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='media/documents/'),
        ),
    ]
