# Generated by Django 3.0.3 on 2020-05-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmltools', '0008_auto_20200426_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='format_valid',
            field=models.CharField(default='INVALID', max_length=10),
        ),
    ]
