# Generated by Django 3.0.3 on 2020-05-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmltools', '0009_document_format_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='profile_file',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
